--CREACION DE ESQUEMA
CREATE SCHEMA biblioteca;
DROP SCHEMA public;

--CREACION DE DOMINIOS
CREATE DOMAIN BIBLIOTECA.ID_LIBRO AS CHAR(6) NOT NULL 
CHECK (VALUE ~ '^[L]{1}[-]{1}\d{4}$');

CREATE DOMAIN BIBLIOTECA.ID_USUARIO AS CHAR(6) NOT NULL 
CHECK (VALUE ~ '^[U]{1}[-]{1}\d{4}$');

CREATE DOMAIN BIBLIOTECA.ID_PRESTAMO AS CHAR(6) NOT NULL 
CHECK (VALUE ~ '^[PR]{1}[-]{1}\d{3}$');


--CREACION DE TABLAS

CREATE TABLE BIBLIOTECA.LIBRO (
pk_idLibro BIBLIOTECA.ID_LIBRO, --NOMBRE DE LA PK Y LE DECIMOS QUE ESTRUCTURA DEBE TENER LA PK CON EL COMINIO
titulo VARCHAR (30) NOT NULL,
autor VARCHAR (30) NOT NULL,
genero VARCHAR (30) NOT NULL,
fechapublicacion INT NOT NULL,
PRIMARY KEY (pk_idLibro)
);


CREATE TABLE BIBLIOTECA.USUARIO (
pk_idUsuario BIBLIOTECA.ID_USUARIO,
nombre VARCHAR (40) NOT NULL,
ciudad VARCHAR (15) NOT NULL,
telefono CHAR(10) UNIQUE NOT NULL,
PRIMARY KEY (pk_idUsuario)
);


CREATE TABLE BIBLIOTECA.PRESTAMO (
pk_idPrestamo BIBLIOTECA.ID_PRESTAMO,
fk_idLibro BIBLIOTECA.ID_LIBRO,
fk_idUsuario BIBLIOTECA.ID_USUARIO,
fechaPrestamo DATE NOT NULL,
fechaDevolucion DATE NOT NULL,
estado VARCHAR (10) NOT NULL,
PRIMARY KEY (pk_idPrestamo),
FOREIGN KEY (pk_idUsuario) REFERENCES BIBLIOTECA.USUARIO (pk_idUsuario)
ON UPDATE CASCADE ON DELETE CASCADE
);




